<?php

return [
    'name' => 'myweb',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
        'backend' => 'zh-cn',
        'frontend' => 'en',
    ],
    'fixedpage' => 'dashboard',
    'categorytype' => [
        'default' => 'Default',
        'page' => 'Page',
        'article' => 'Article',
        'test' => 'Test',
    ],
    'configgroup' => [
        'bankpay' => 'BankPay',
        'USDT' => 'USDT',
        'basic' => 'Basic',
        'email' => 'Email',
        'dictionary' => 'Dictionary',
        'user' => 'User',
        'example' => 'Example',
    ],
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.gmail.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => 'qli86046@gmail.com',
    'mail_smtp_pass' => 'qwe112211.',
    'mail_verify_type' => '2',
    'mail_from' => 'trtrt@gmail.com',
    'linegroup' => '{}',
    'bank_kaihu' => '儲值请联絡客服line ID:',
    'bank_add' => '儲值请联絡客服line ID:s',
    'bank_num' => '儲值请联絡客服line ID:',
    'recharge_money' => '0',
    'luodiurl' => 'https://h5.w.com/down/index.html',
    'payisok' => '0',
    'usdt_type' => 'TRC20',
    'usdt_qr' => '/uploads/20210712/0a4834287827c75a422a04eb0eca0891.jpg',
    'usdt_add' => 'TDGLdgRSiwetxmJwUWgeR4Ksbgy8srMB7e',
    'usdt_er' => '27.894',
    'usdt_tips' => 'USDT提示',
];
